name: Pull Request Update Body Action
description: Prepend to or override a pull request's body
branding:
  icon: award
  color: red
inputs:
  ghToken:
    description: GitHub token
    required: true
  body:
    description: Text to be prepended to the body
    required: true
  override:
    description: Should the body get overriden
    required: false
runs:
  using: "node12"
  main: "index.js"
